const axios = require('axios');

async function executeDirectDueDiligence() {
    console.log('🔥 DIRECT DUE DILIGENCE EXECUTION - NO N8N!');
    console.log('===========================================\n');
    
    try {
        // Step 1: Get all tasks from Kanboard
        console.log('1. 📋 Getting tasks from Kanboard...');
        const tasksResponse = await axios.post('http://localhost:8000/jsonrpc.php', {
            jsonrpc: "2.0",
            method: "getAllTasks",
            id: 1,
            params: { project_id: 1 }
        }, {
            auth: { username: 'admin', password: 'admin' },
            headers: { 'Content-Type': 'application/json' }
        });

        const allTasks = tasksResponse.data.result;
        console.log(`✅ Retrieved ${allTasks.length} total tasks`);
        
        // Step 2: Filter for Due Diligence tasks
        const dueDiligenceTasks = allTasks.filter(task => 
            task.title.includes('Due Diligence')
        );
        
        console.log(`🎯 Found ${dueDiligenceTasks.length} Due Diligence tasks\n`);
        
        if (dueDiligenceTasks.length === 0) {
            console.log('❌ No Due Diligence tasks found!');
            return;
        }
        
        // Step 3: Process each Due Diligence task
        const sections = [
            "Executive Summary",
            "Company Overview", 
            "Market Analysis",
            "Financial Performance",
            "Risk Assessment",
            "Investment Recommendation"
        ];
        
        for (let taskIndex = 0; taskIndex < dueDiligenceTasks.length; taskIndex++) {
            const task = dueDiligenceTasks[taskIndex];
            console.log(`\n🏢 Processing Task ${taskIndex + 1}: "${task.title}"`);
            console.log(`   ID: ${task.id}`);
            
            // Process each section for this task
            for (let sectionIndex = 0; sectionIndex < sections.length; sectionIndex++) {
                const section = sections[sectionIndex];
                console.log(`\n   📊 Section ${sectionIndex + 1}: ${section}`);
                
                try {
                    // Generate AI content
                    console.log(`      🤖 Generating AI content...`);
                    const aiResponse = await axios.post('http://localhost:11434/api/generate', {
                        model: "mistral:latest",
                        prompt: `Generate a comprehensive ${section} analysis for: ${task.title}. Provide detailed professional analysis with specific insights, recommendations, and key findings. Format in clean markdown with headers and bullet points. Minimum 200 words.`,
                        stream: false
                    }, { timeout: 60000 });
                    
                    const aiContent = aiResponse.data.response;
                    console.log(`      ✅ Generated ${aiContent.length} characters`);
                    
                    // Post comment to Kanboard
                    console.log(`      📝 Posting to Kanboard...`);
                    const commentResponse = await axios.post('http://localhost:8000/jsonrpc.php', {
                        jsonrpc: "2.0",
                        method: "createComment",
                        id: 1,
                        params: {
                            task_id: task.id,
                            content: `## 📊 ${section}\n\n${aiContent}\n\n---\n*Generated by AI Due Diligence System - ${new Date().toISOString()}*`,
                            user_id: 1
                        }
                    }, {
                        auth: { username: 'admin', password: 'admin' },
                        headers: { 'Content-Type': 'application/json' }
                    });
                    
                    if (commentResponse.data.result) {
                        console.log(`      ✅ Comment posted (ID: ${commentResponse.data.result})`);
                    } else {
                        console.log(`      ❌ Comment failed:`, commentResponse.data);
                    }
                    
                } catch (sectionError) {
                    console.log(`      ❌ Section failed: ${sectionError.message}`);
                }
                
                // Small delay between sections
                await new Promise(resolve => setTimeout(resolve, 1000));
            }
            
            console.log(`   ✅ Completed all sections for "${task.title}"`);
        }
        
        console.log('\n🎉 DUE DILIGENCE EXECUTION COMPLETE!');
        console.log('===================================');
        console.log(`✅ Processed ${dueDiligenceTasks.length} companies`);
        console.log(`✅ Generated ${dueDiligenceTasks.length * sections.length} AI sections`);
        console.log(`✅ Posted all comments to Kanboard`);
        console.log('✅ NO WORKFLOW NEEDED - DIRECT EXECUTION!');
        
    } catch (error) {
        console.error('❌ Execution failed:', error.message);
        if (error.response?.data) {
            console.error('Response data:', error.response.data);
        }
    }
}

// Execute immediately
executeDirectDueDiligence();
