version: '3.8'

x-db-env: &db-env
  PGHOST: plane-db
  PGDATABASE: plane
  POSTGRES_USER: plane
  POSTGRES_PASSWORD: plane
  POSTGRES_DB: plane
  POSTGRES_PORT: 5432

x-redis-env: &redis-env
  REDIS_HOST: plane-redis
  REDIS_PORT: 6379
  REDIS_URL: redis://plane-redis:6379/

x-minio-env: &minio-env
  MINIO_ROOT_USER: access-key
  MINIO_ROOT_PASSWORD: secret-key

x-aws-s3-env: &aws-s3-env
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: access-key
  AWS_SECRET_ACCESS_KEY: secret-key
  AWS_S3_ENDPOINT_URL: http://plane-minio:9000
  AWS_S3_BUCKET_NAME: uploads

x-app-env: &app-env
  WEB_URL: http://localhost:3001
  DEBUG: 0
  GUNICORN_WORKERS: 1
  USE_MINIO: 1
  DATABASE_URL: postgresql://plane:plane@plane-db/plane
  SECRET_KEY: 60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5
  MINIO_ENDPOINT_SSL: 0

services:
  plane-db:
    image: postgres:15.7-alpine
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    environment:
      <<: *db-env
    volumes:
      - plane_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  plane-redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - plane_redis_data:/data
    ports:
      - "6380:6379"

  plane-minio:
    image: minio/minio:latest
    command: server /export --console-address ":9090"
    restart: unless-stopped
    environment:
      <<: *minio-env
    volumes:
      - plane_minio_data:/export
    ports:
      - "9000:9000"
      - "9090:9090"

  plane-api:
    image: makeplane/plane-backend:stable
    restart: unless-stopped
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      <<: [*app-env, *db-env, *redis-env, *aws-s3-env]
    depends_on:
      - plane-db
      - plane-redis
      - plane-minio
    ports:
      - "8000:8000"
    volumes:
      - plane_api_logs:/code/plane/logs

  plane-worker:
    image: makeplane/plane-backend:stable
    restart: unless-stopped
    command: celery -A plane worker -l info
    environment:
      <<: [*app-env, *db-env, *redis-env, *aws-s3-env]
    depends_on:
      - plane-api
      - plane-db
      - plane-redis
    volumes:
      - plane_worker_logs:/code/plane/logs

  plane-beat-worker:
    image: makeplane/plane-backend:stable
    restart: unless-stopped
    command: celery -A plane beat -l info
    environment:
      <<: [*app-env, *db-env, *redis-env, *aws-s3-env]
    depends_on:
      - plane-api
      - plane-db
      - plane-redis
    volumes:
      - plane_beat_logs:/code/plane/logs

  plane-frontend:
    image: makeplane/plane-frontend:stable
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - plane-api
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000

volumes:
  plane_db_data:
  plane_redis_data:
  plane_minio_data:
  plane_api_logs:
  plane_worker_logs:
  plane_beat_logs:

networks:
  default:
    name: plane-network
