# Frontend Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm install --production
RUN npm run build
EXPOSE 3000
CMD ["npx", "serve", "-s", "build", "-l", "3000"]
