$clientId = "68cfa7f9d648485bef38b943"  # GreenLeaf Analytics

Write-Host "Testing contracts API for client: $clientId"
Write-Host "="*50

try {
    $response = Invoke-RestMethod -Uri "http://localhost:10000/api/clients/$clientId/contracts" -Method GET
    
    Write-Host "API Response received successfully!"
    Write-Host "Client Name: $($response.client_name)"
    Write-Host "Client ID: $($response.client_id)"
    Write-Host "Number of contracts: $($response.contracts.Count)"
    Write-Host ""
    
    if ($response.contracts.Count -gt 0) {
        Write-Host "Contract Details:"
        Write-Host "-"*30
        
        for ($i = 0; $i -lt $response.contracts.Count; $i++) {
            $contract = $response.contracts[$i]
            Write-Host "Contract #$($i + 1):"
            Write-Host "  Generated At: $($contract.generated_at)"
            Write-Host "  Generated By: $($contract.generated_by)"
            Write-Host "  Request ID: $($contract.request_id)"
            Write-Host "  Content Length: $($contract.content.Length) characters"
            Write-Host "  Content Preview: $($contract.content.Substring(0, [Math]::Min(100, $contract.content.Length)))..."
            Write-Host ""
        }
    } else {
        Write-Host "No contracts found for this client."
    }
    
} catch {
    Write-Host "Error testing contracts API: $($_.Exception.Message)"
    Write-Host "Status Code: $($_.Exception.Response.StatusCode)"
}
