# Test @CG workflow components manually
$headers = @{ 
    'Authorization' = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes('admin:admin'))
    'Content-Type' = 'application/json' 
}

Write-Host "=== Testing @CG Workflow Components ===" -ForegroundColor Yellow

# Step 1: Get tasks from clients project (ID: 5)
Write-Host "`n1. Getting tasks from clients project..." -ForegroundColor Cyan
$tasksBody = '{"jsonrpc":"2.0","method":"getAllTasks","id":1,"params":{"project_id":5,"status_id":1}}'
$tasks = Invoke-RestMethod -Uri 'http://localhost:8000/jsonrpc.php' -Method POST -Headers $headers -Body $tasksBody

Write-Host "Found $($tasks.result.Count) tasks:" -ForegroundColor Green
$tasks.result | ForEach-Object { 
    Write-Host "- ID: $($_.id), Title: '$($_.title)'" 
    if ($_.description) {
        Write-Host "  Description: $($_.description)" -ForegroundColor Gray
    }
}

# Step 2: Find @CG tasks
Write-Host "`n2. Looking for @CG tasks..." -ForegroundColor Cyan
$cgTasks = $tasks.result | Where-Object { 
    $_.title -match '@CG' -or $_.description -match '@CG' 
}

if ($cgTasks) {
    Write-Host "Found $($cgTasks.Count) @CG tasks:" -ForegroundColor Green
    $cgTasks | ForEach-Object {
        Write-Host "- Task ID: $($_.id)" -ForegroundColor Yellow
        Write-Host "  Title: $($_.title)" -ForegroundColor White
        Write-Host "  Description: $($_.description)" -ForegroundColor Gray
        
        # Extract company name (everything before @CG)
        $companyName = $_.title.Split('@CG')[0].Trim()
        Write-Host "  Company: $companyName" -ForegroundColor Magenta
    }
    
    # Step 3: Test comment creation for the first @CG task
    Write-Host "`n3. Testing comment creation..." -ForegroundColor Cyan
    $firstCgTask = $cgTasks[0]
    $testComment = "🧪 **Test @CG Response**`n`nThis is a test response to verify the workflow is working.`n`n**Search Results:** Testing Pinecone integration...`n`n**Key Information:** Sample response`n`n**Generated on:** $(Get-Date)`n`n---`n💡 *This response was generated by searching our Pinecone vector database.*"
    
    $commentBody = @{
        jsonrpc = "2.0"
        method = "createComment"
        id = 1
        params = @{
            task_id = $firstCgTask.id.ToString()
            content = $testComment
            user_id = 1
        }
    } | ConvertTo-Json -Depth 3
    
    $commentResult = Invoke-RestMethod -Uri 'http://localhost:8000/jsonrpc.php' -Method POST -Headers $headers -Body $commentBody
    Write-Host "Comment created with ID: $($commentResult.result)" -ForegroundColor Green
    
} else {
    Write-Host "No @CG tasks found!" -ForegroundColor Red
}

Write-Host "`n=== Test Complete ===" -ForegroundColor Yellow
