# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

sys.path.insert(0, os.path.abspath('../../'))
sys.path.insert(0, os.path.abspath('../../backend'))
sys.path.insert(0, os.path.abspath('../../api'))
sys.path.insert(0, os.path.abspath('../../rag-app'))

# -- Project information -----------------------------------------------------

project = 'The Genius Project'
copyright = '2025, Rabab'
author = 'Rabab'
release = '1.0.0'
version = '1.0.0'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'autoapi.extension',
]

# AutoAPI configuration
autoapi_type = 'python'
autoapi_dirs = ['../../backend', '../../api', '../../rag-app']
autoapi_root = 'api'
autoapi_add_toctree_entry = True
autoapi_generate_api_docs = True
autoapi_options = [
    'members',
    'undoc-members', 
    'show-inheritance',
    'show-module-summary',
    'special-members',
    'imported-members',
]
autoapi_ignore = [
    '*migrations*',
    '*venv*',
    '*__pycache__*',
    '*/.*',
    '*test*',
    '*Test*',
    '*broken*',
    '*old*',
    '*_old*',
    '*debug*',
    '*_debug*',
    '*mock*',
    '*temp*',
    '*/alembic/*',
    '*/instance/*',
    '*/uploads/*',
    '*/logs/*',
    '*/create_test*',
    '*/setup_test*',
    '*/cleanup_test*',
    '*/migrate*',
    '*/check_users*',
    '*/models_new*',
    '*/app_clean*',
    '*/app_simple*',
    '*client_ai_routes_broken*',
    '*client_ai_routes_old*'
]

# Napoleon settings for Google/NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'furo'

# Theme options are theme-specific and customize the look and feel of a theme
# further.
html_theme_options = {
    "sidebar_hide_name": False,
    "light_logo": "logo-light.png",
    "dark_logo": "logo-dark.png",
    "light_css_variables": {
        "color-brand-primary": "#FFD700",
        "color-brand-content": "#FFD700",
    },
    "dark_css_variables": {
        "color-brand-primary": "#FFD700",
        "color-brand-content": "#FFD700",
    },
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# A list of ignored prefixes for module index sorting.
modindex_common_prefix = ['backend.', 'api.', 'rag-app.']

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'letterpaper',
    
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',
    
    # Additional stuff for the LaTeX preamble.
    'preamble': '',
    
    # Latex figure (float) alignment
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'TheGeniusProject.tex', 'The Genius Project Documentation',
     'Rabab', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'thegeniusproject', 'The Genius Project Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'TheGeniusProject', 'The Genius Project Documentation',
     author, 'TheGeniusProject', 'One line description of project.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Intersphinx mapping -----------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'flask': ('https://flask.palletsprojects.com/en/2.0.x/', None),
    'sqlalchemy': ('https://docs.sqlalchemy.org/en/14/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
}

# -- AutoDoc configuration ---------------------------------------------------

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

autodoc_mock_imports = [
    'flask_migrate',
    'flask_cors',
    'flask_bcrypt',
    'flask_socketio',
    'pymongo',
    'pinecone',
    'openai',
    'langchain',
    'chromadb',
    'ollama',
    'sentence_transformers',
    'transformers',
    'torch',
    'numpy',
    'pandas',
    'requests',
    'python-dotenv',
    'bcrypt',
    'jwt',
    'werkzeug',
    'psycopg2',
    'sqlalchemy',
    'alembic',
    'pytest',
    'fastapi',
    'uvicorn',
    'pydantic'
]
