name: Deploy Python Flask + React

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1-7. [Keep all your existing build/test steps here]
      
      # 8. Fixed Vercel deployment step
      - name: Deploy Frontend to Vercel
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd frontend
          # Install latest Vercel CLI explicitly
          npm install -g vercel@latest
          # Deploy with all required flags
          vercel deploy --prod --token=$VERCEL_TOKEN --yes 2>&1 | tee deploy.log
          # Print deployment URL
          cat deploy.log | grep -o 'https://[^ ]*' | head -1
