"""Add user_type and department to User model

Revision ID: cc2bb65baa31
Revises: 2b24e031795e
Create Date: 2025-07-01 15:03:35.459858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2bb65baa31'
down_revision = '2b24e031795e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
    # Set NOT NULL constraint after populating existing rows
    op.execute("UPDATE users SET user_type = 'employee' WHERE user_type IS NULL;")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
